### ISSUE TITLE
Implement an "Assign me" shortcut

### ISSUE THREAD

**Issue by ianpittwood** [ianpittwood/Gerrit-to-Github-Issues#5]
Implement and "Assign me" shortcut to allow users without proper project permissions to assign issues to themselves. The shortcut should be able to be triggered by commenting on the issue with a shortcut like "!assignme". The shortcut should be ignored if the issue is already assigned and not stale and should instead notify the core team of the attempted use of the shortcut to evaluate if the assignment should be switched over.

**Comment by ian-howell** [comment]
!assignme

haha but seriously, go ahead and assign me.
